// <auto-generated/>
global using global::Microsoft.AspNetCore.Builder;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Http;
global using global::Microsoft.AspNetCore.Routing;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Threading.Tasks;
global using OnionApiUpgradeBogus.Application.Exceptions;
global using OnionApiUpgradeBogus.Application.Features.Customers.Commands.CreateCustomer;
global using OnionApiUpgradeBogus.Application.Features.Customers.Commands.DeleteCustomerById;
global using OnionApiUpgradeBogus.Application.Features.Customers.Commands.UpdateCustomer;
global using OnionApiUpgradeBogus.Application.Features.Customers.Queries.GetCustomerById;
global using OnionApiUpgradeBogus.Application.Features.Customers.Queries.GetCustomers;
global using OnionApiUpgradeBogus.Application.Features.Employees.Queries.GetEmployees;
global using OnionApiUpgradeBogus.Application.Features.Positions.Commands.CreatePosition;
global using OnionApiUpgradeBogus.Application.Features.Positions.Commands.DeletePositionById;
global using OnionApiUpgradeBogus.Application.Features.Positions.Commands.UpdatePosition;
global using OnionApiUpgradeBogus.Application.Features.Positions.Queries.GetPositionById;
global using OnionApiUpgradeBogus.Application.Features.Positions.Queries.GetPositions;
global using OnionApiUpgradeBogus.Application.Wrappers;
global using System.Net;
global using System.Text.Json;


